name: Publish

on:
  push:
    tags: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            asset: deb/Voicee_${{ github.ref_name }}_amd64.deb
            features: '-- --features cuda'
          - os: macos-latest
            target: aarch64-apple-darwin
            asset: dmg/Voicee_${{ github.ref_name }}_aarch64.dmg
            features: '-- --features metal'
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            asset: msi/Voicee_${{ github.ref_name }}_x64_en-US.msi
            features: '-- --features cuda'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      # 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      # 安装系统依赖 (仅在 Ubuntu 上)
      - name: Install system dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libsoup-3.0-dev libjavascriptcoregtk-4.1-dev build-essential curl wget file libssl-dev libxdo-dev

      # 安装 CUDA
      - name: Install CUDA
        if: matrix.os == 'ubuntu-22.04' || matrix.os == 'windows-latest'
        uses: Jimver/cuda-toolkit@v0.2.30
        id: cuda-toolkit
        with:
          cuda: '12.6'
          method: 'local'

      # 安装前端依赖
      - name: Install frontend dependencies
        run: npm ci

      # 设置前端版本号
      - name: Set frontend version
        if: matrix.os != 'macos-latest'
        run: sed -i "s/^VITE_VERSION=.*/VITE_VERSION=${{ github.ref_name }}/" .env.production

      # 设置前端版本号
      - name: Set frontend version
        if: matrix.os == 'macos-latest'
        run: sed -i '' "s/^VITE_VERSION=.*/VITE_VERSION=${{ github.ref_name }}/" .env.production

      # 构建
      - name: Build App
        run: npm run tauri build ${{ matrix.features }}

      # 创建 Release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            src-tauri/target/release/bundle/${{ matrix.asset }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}